### ISSUE TITLE
Basic.py throws a TypeError

### ISSUE THREAD

**Issue by mkpathcreate** [vallettea/koala#130]
When I run the examples/basic.py it shows a TypeError.

user@webserver: python3 examples/basic.py 

./examples/basic.xlsx
___### Initializing Excel Compiler ###___
___### Reading Cells from XLSX ###___
Nb of different functions 0
set()
___### Generating Graph ###___
Seeds 66 cells
Graph construction done, 86 nodes, 74 edges, 86 cellmap entries
Serializing to disk...
Traceback (most recent call last):
  File "examples/basic.py", line 16, in <module>
    sp.dump(filename.replace("xlsx", "gzip"))
  File "/usr/local/lib/python3.5/dist-packages/koala/Spreadsheet.py", line 442, in dump
    dump(self, fname)
  File "/usr/local/lib/python3.5/dist-packages/koala/serializer.py", line 58, in dump
    outfile.write(str(cell.value) + "\n")
  File "/usr/lib/python3.5/gzip.py", line 258, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'

**Comment by vallettea** [comment]
It works fine under python 2.7 so I guess it is related to python 3. I'm not familiar to python 3 but maybe @jricardo27 or @Brad-eki can help.

**Comment by jricardo27** [comment]
In Python 2 byte strings and text strings are the same unlike Python 3 where they are clearly differentiated.

Change line 58 in `koala/serializer.py` from:
```
outfile.write(str(cell.value) + "\n")
```

to:
```
outfile.write((str(cell.value) + "\n").encode('utf-8'))
```

That should be a quick fix, a better solution is to refactor the code and stop mixing unicode, text strings and bytes. Apologies if I don't offer to do it.

The long explanation is that `outfile` is open as a binary file and it expects bytes to be written on it, you probably can open the file in text mode and remove all the `encode()` when writing to it:

From this:
```
outfile = gzip.GzipFile(fname, 'w')
```

to this:
```
outfile = gzip.GzipFile(fname, mode='wt')
```

**Comment by Brad-eki** [comment]
Hi Guys,

In Python 3 strings are natively UTF-8 so attempting to consciously encode them to UTF-8 in Python 3 causes problems. To state the obvious, in Python 2 strings are not UTF-8 encoded.

Due to this bug report it appears I may have introduced a regression, made an inadequate fix or may have missed something in the excitement to support Python 3.

We may well reap great benefit from a re-factor as suggested by @jricardo27 which I suspect will aid the preservation of backwards compatibility.

As it appears this has slipped through, we may want to re-assess my changes and likely upgrade the tests to catch this case.

I am interested in attempting a fix but I can’t make time to start on it until late in the weekend at the earliest.

Cheers

**Comment by Brad-eki** [comment]
I have re-created the exception. Having a _very_ quick look, the tests don't cover the serializer dump method which is where the bug is being triggered.

**Comment by mkpathcreate** [comment]
We fixed the str to bytes issue by converting it. Now basic.py and advance.py works in 3.5, but might not work in 2.x.

https://github.com/mkpathcreate/koala/commit/641e4cf44e30fccbf3374d41005065be18bbf03d

**Comment by Brad-eki** [comment]
I've run your fix in 2.7 and 3.6. Basic.py is working. Advanced.py is breaking for me. It's an issue with netowrkx 2.1 upgrade that I have missed... Spreadsheet.py still has a couple of graph.predecessors_iter() calls.

Lesson learned: Run the tests and all examples for a more comprehensive exercise of the code. Apologies for the half job.

Traceback (most recent call last):
  File "examples/advanced.py", line 68, in <module>
    alive = sp.detect_alive(inputs = inputs, outputs = outputs)
  File "C:\{obscured}\koala\Spreadsheet.py", line 318, in detect_alive
    pointer_arguments = self.find_pointer_arguments(outputs)
  File "C:\{obscured}\koala\Spreadsheet.py", line 370, in find_pointer_arguments
    for parent in self.G.predecessors_iter(cell): # climb up the tree
AttributeError: 'DiGraph' object has no attribute 'predecessors_iter'

mkpathcreate, did you have changes for Spreadsheet.py lines 370 and 556?

**Comment by mkpathcreate** [comment]
Yes we had changed predecessors_iter to predecessors.
Sorry forgot to mention it in previous post.

https://github.com/mkpathcreate/koala/commit/b9c85af1f829252eb9dbc9894f4680ff850d6174

**Comment by Brad-eki** [comment]
I have taken the zip version b9c85af from mkpathcreate and successfully executed all tests and run both Basic and Advanced examples in Python 2.7, 3.4, 3.5 and 3.6.

Thanks mkpathcreate

**Comment by vallettea** [comment]
@mkpathcreate could you make a PR with the working version so we can close this issue ?
thanks

**Comment by Brad-eki** [comment]
Would I be committing a faux pas if I were to prepare a pull request with changes from mkpathcreate?

**Comment by vallettea** [comment]
Not at all!

Envoyé de mon iPhone

**Comment by Brad-eki** [comment]
mkpathcreate, thanks mate. I really appreciate the fixes (and so do my co-workers).

My contribution to Koala was the first I've made to an open source project, let alone using github. It's all pretty foreign.

Cheers.
